### ISSUE TITLE
I can help with macos support 

### ISSUE THREAD

**Issue by JonnycatMeow** [SanicBTW/HxWebView#2]
contact me at my discord jonnycat

**Comment by SanicBTW** [comment]
Yeah that would help a lot! I'll add you asap, let's continue talkin thru Discord

**Comment by ZSolarDev** [comment]
is this still being worked on? i need the dev branch for macos so i can control the window on macos but its not done yett

**Comment by SanicBTW** [comment]
I'm afraid due to the lack of my communication with Jonny we never got to work on binds (well I never told him if he could work on those honestly) all I got was some flag for the WebView controller on MacOS and pushed it to the master branch, since then I never really updated anything else and there's still stuff to do on the dev branch.
My best approach is to get some Mac virtual machine and figure out the bindings by myself, even if it's messy

**Comment by ZSolarDev** [comment]
Hi, so macos virtual machines are actually so difficult to set up if you're doing it for the first time. I already have one set up, so if you ever do want to get the bindings working, I can help with the bindings as well as testing them! As long as you're down for it, I'm down for it

**Comment by SanicBTW** [comment]
Oh yeah, I created only one Mac VM in the past but barely used it, so uhh it sounds good, yeah let's go for it, thanks for the help!
Talk to me thru discord and we'll get working on the bindings: _sanco

**Comment by JonnycatMeow** [comment]
sorry Im not into porting anymore and I have to get a new Macbook

**Comment by SanicBTW** [comment]
It's okay, my bad for not taking in the help you offered, I'll be figuring something out and I'll try to be in touch with ZSolarDev.

Just a quick question, did you even get to run the library and get content rendered to it? All I get is an empty window

**Comment by JonnycatMeow** [comment]
I think I got it ran but idk I gotta run the application again
